
const nodemailer = require("nodemailer");


const sendmail=async(req,res)=>{

    let testAccount = await nodemailer.createTestAccount();


    let transporter =  await nodemailer.createTransport({
        host: "smtp.ethereal.email",
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: 'clotilde.bins2@ethereal.email',
            pass: 'BVun6rBHt7rBTSfXGc'
        },
      });


      let info = await transporter.sendMail({
        from: '"devgru 👻" <clotilde.bins2@ethereal.email>', // sender address
        to: "noveen.madhu.0707@gmail.com", // list of receivers
        subject: "Hello ✔", // Subject line
        text: "this is demo message generated by noveen madhu for testing", // plain text body
        html: "<b>el dorado</b>", // html body
      });

      console.log("Message sent: %s", info.messageId);

    res.json(info)
}

module.exports=sendmail